import type { ProjectDetail } from "@/types"

const activeMembers = [
	{
		id: 1,
		name: "박소은",
		studentNumber: "2021-23456",
		isLeader: true,
		position: "PM, 디자이너(WAFFICE)",
		email: "waffice@gmail.com",
		githubId: "wafflestudio",
		status: "활동 중",
		startDate: "2025.10.01",
		endDate: "2025.11.27",
	},
	{
		id: 2,
		name: "홍길동",
		studentNumber: "2022-11111",
		isLeader: false,
		position: "백엔드(WAFFICE)",
		email: "server@waffle.studio",
		githubId: "waffle-server",
		status: "활동 중",
		startDate: "2025.10.01",
		endDate: "2025.11.27",
	},
	{
		id: 3,
		name: "김와플",
		studentNumber: "2021-23456",
		isLeader: false,
		position: "프론트엔드(WAFFICE)",
		email: "frontend@waffle.studio",
		githubId: "waffle-web",
		status: "활동 중",
		startDate: "2025.10.01",
		endDate: "2025.11.27",
	},
	{
		id: 4,
		name: "이시럽",
		studentNumber: "2023-56789",
		isLeader: false,
		position: "디자이너(WAFFICE)",
		email: "design@waffle.studio",
		githubId: "waffle-design",
		status: "활동 중",
		startDate: "2025.10.01",
		endDate: "2025.11.27",
	},
	{
		id: 5,
		name: "정메이플",
		studentNumber: "2020-98765",
		isLeader: false,
		position: "iOS(WAFFICE)",
		email: "ios@waffle.studio",
		githubId: "waffle-ios",
		status: "활동 중",
		startDate: "2025.10.01",
		endDate: "미정",
		endDatePending: true,
	},
] satisfies ProjectDetail["activeMembers"]

const pastMembers = [
	{
		id: 101,
		name: "최아카이브",
		studentNumber: "2019-10101",
		isLeader: true,
		position: "PM(WAFFICE)",
		email: "archive.pm@waffle.studio",
		githubId: "waffle-archive-pm",
		status: "비활성화",
		startDate: "2024.03.01",
		endDate: "2024.12.20",
	},
	{
		id: 102,
		name: "오레거시",
		studentNumber: "2019-22222",
		isLeader: false,
		position: "백엔드(WAFFICE)",
		email: "legacy.server@waffle.studio",
		githubId: "waffle-legacy",
		status: "비활성화",
		startDate: "2024.03.01",
		endDate: "2024.12.20",
	},
	{
		id: 103,
		name: "문히스토리",
		studentNumber: "2020-33333",
		isLeader: false,
		position: "프론트엔드(WAFFICE)",
		email: "history.web@waffle.studio",
		githubId: "waffle-history",
		status: "비활성화",
		startDate: "2024.07.01",
		endDate: "2025.02.28",
	},
] satisfies ProjectDetail["pastMembers"]

export const MOCK_PROJECT_DETAIL: ProjectDetail = {
	id: 1,
	name: "인터널 프로덕트",
	status: "활성화",
	activeMembers,
	pastMembers,
	linkGroups: [
		{
			name: "Released",
			links: [
				{
					id: 1,
					type: "Web",
					label: "와플 스튜디오 관리 시스템",
					url: "https://waffle.studio",
				},
				{
					id: 2,
					type: "iOS",
					label: "App Store SNUTT : 서울대학교 시간표 앱",
					url: "https://apps.apple.com",
				},
				{
					id: 3,
					type: "Android",
					label: "GooglePlay SNUTT2: 서울대학교 시간표 작성!",
					url: "https://play.google.com",
				},
			],
		},
		{
			name: "Github",
			links: [
				{
					id: 4,
					type: "Web",
					label: "GitHub wafflestudio/waffice-web",
					url: "https://github.com/wafflestudio/waffice-web",
				},
				{
					id: 5,
					type: "Server",
					label: "GitHub wafflestudio/waffice-fastapi",
					url: "https://github.com/wafflestudio/waffice-fastapi",
				},
			],
		},
		{
			name: "ETC",
			links: [],
		},
	],
	statusHistories: [
		{ status: "활성화", startDate: "2025.10.01", endDate: "2026.10.01" },
		{ status: "유지보수", startDate: "2024.10.01", endDate: "2025.10.01" },
	],
}
